language: r
cache: packages
addons:
   apt:
     packages:
       - libgsl0-dev 
       - libxml2-dev
       - libv8-dev

before_install:
  r_packages:
    - DCluster
    - jsonlite
    - RCurl
    - jsonlite
    - rgdal
    - rgeos
    - ggplot2
    - ggmap
    - RColorBrewer
    - stringr
    - scales
    - geojsonio
    - downloader
    - spdep
    - viridis
    - maptools
    - rvest
    - dplyr
    - stringr
    - stringi
    - geojsonio
    - knitr

install:
  - Rscript -e "library(knitr); knit('post.Rmd')" 

