language: r
cache: packages
addons:
   apt:
     packages:
       - libgsl0-dev 
       - libxml2-dev
       - libv8-dev

r_packages:
  - DCluster
  - jsonlite
  - RCurl
  - jsonlite
  - rgdal
  - rgeos
  - ggplot2
  - ggmap
  - RColorBrewer
  - stringr
  - scales
  - geojsonio
  - downloader
  - spdep
  - viridis
  - maptools
  - rvest
  - dplyr
  - stringr
  - stringi
  - geojsonio
  - knitr

install:
  - Rscript -e "library(knitr); stitch('post.Rmd')" 

